# WSL cross-compilation
[env]
CC_aarch64_unknown_linux_musl = "/home/mone/bin/aarch64-ohos-clang"
AR_aarch64_unknown_linux_musl = "/home/mone/bin/ohos-ar"
CC_x86_64_unknown_linux_musl = "gcc"
AR_x86_64_unknown_linux_musl = "ar"
CFLAGS_aarch64_unknown_linux_musl = "--sysroot=/home/mone/ohos-ndk/sysroot"

[target.aarch64-unknown-linux-musl]
linker = "/home/mone/bin/aarch64-ohos-clang"
rustflags = [
    "-C", "link-arg=--sysroot=/home/mone/ohos-ndk/sysroot",
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-static",
    "-C", "target-feature=+crt-static",
]

[target.x86_64-unknown-linux-musl]
linker = "/home/mone/bin/x86_64-ohos-clang"
rustflags = [
    "-C", "link-arg=--sysroot=/home/mone/ohos-ndk/sysroot",
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-static",
    "-C", "target-feature=+crt-static",
]
