/**
 * Auto-generated by cbindgen from rust_core/agent_core.
 * DO NOT EDIT.
 */

#ifndef AGENT_CORE_H
#define AGENT_CORE_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// --- Function pointer type aliases ---
typedef char* (*PostFn)(const char* url, const char* body);
typedef bool (*StreamPostFn)(const char* url, const char* body,
                              void (*on_chunk)(const char* chunk_data, uint8_t event_type));
typedef void (*FreeStrFn)(char* ptr);

// --- SystemCallbacks: host IO capabilities injected at init ---
typedef struct {
    PostFn post_fn;
    StreamPostFn stream_post_fn;
    FreeStrFn free_str_fn;
} SystemCallbacks;

// --- FFI function declarations ---
bool rust_agent_init(SystemCallbacks callbacks);
char* rust_agent_call(const char* action, const char* json_args);
void rust_agent_free_str(char* ptr);
void rust_agent_register_stream_cb(void (*callback)(const char* chunk_data, uint8_t event_type));

// --- Sandbox validation ---
bool test_network(void);
bool test_file(const char* dir);

#ifdef __cplusplus
}
#endif

#endif // AGENT_CORE_H
