/**
 * Auto-generated by cbindgen from rust_core/agent_core.
 * DO NOT EDIT.
 */

#ifndef AGENT_CORE_H
#define AGENT_CORE_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// --- Function pointer type aliases ---
typedef char* (*PostFn)(const char* url, const char* body);
typedef bool (*StreamPostFn)(const char* url, const char* body,
                              void (*on_chunk)(const char* chunk_data, uint8_t event_type));
typedef void (*FreeStrFn)(char* ptr);
typedef void (*PermissionFn)(const char* tool_name, const char* reason);

// --- SystemCallbacks: host IO capabilities injected at init ---
typedef struct {
    PostFn post_fn;
    StreamPostFn stream_post_fn;
    FreeStrFn free_str_fn;
} SystemCallbacks;

// --- FFI function declarations ---
bool rust_agent_init(SystemCallbacks callbacks);
char* rust_agent_call(const char* action, const char* json_args);
void rust_agent_free_str(char* ptr);
void rust_agent_register_stream_cb(void (*callback)(const char* chunk_data, uint8_t event_type));

// --- Sandbox validation ---
bool test_network(void);
bool test_file(const char* dir);

// --- Phase 1: search & RAG ---
// Returns JSON array of search matches. Caller must free via rust_agent_free_str.
char* rust_agent_search(const char* dir_path, const char* pattern);
// Returns JSON status. Caller must free via rust_agent_free_str.
char* rust_agent_scan_dir(const char* dir_path);

// --- Phase 7: Permission callbacks ---
void rust_agent_set_permission_cb(PermissionFn cb);
void rust_agent_resolve_permission(bool allowed);

#ifdef __cplusplus
}
#endif

#endif // AGENT_CORE_H
